name: Build

on:
  - push
  - pull_request

jobs:
  npm:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Set Yarn version
        run: yarn policies set-version v1.22.19
      - name: Compile
        run: npm run build
